<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8AF4MIK" failures="1" tests="1" name="testPackage.TC_002_LogOut" time="4.156" errors="0" timestamp="2024-11-19T09:53:50 IST" skipped="0">
  <testcase classname="testPackage.TC_002_LogOut" name="validateLogOut" time="4.156">
    <failure message="expected [https://allteacher.navadhiti.com/dashboar] but found [https://allteacher.navadhiti.com/dashboard]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://allteacher.navadhiti.com/dashboar] but found [https://allteacher.navadhiti.com/dashboard]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at pageObjects.PG_002_LogOut.verify_the_Results(PG_002_LogOut.java:39)
at testPackage.TC_002_LogOut.validateLogOut(TC_002_LogOut.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateLogOut -->
</testsuite> <!-- testPackage.TC_002_LogOut -->
